#!/usr/bin/env python2
# -*- mode: python ; coding: utf-8 -*-
#
# Copyright © 2012–2013 Roland Sieker <ospalh@gmail.com>
#
# License: GNU AGPL, version 3 or later;
# http://www.gnu.org/copyleft/agpl.html

"""
Turn a video and sets of subtitles into an Anki2 deck.
"""

from jimakuanki import JimakuAnki
import argparse

def setup_from_args(ma, args):
    ma.out_file = ma.fix_path(args.output)
    ma.deck_id = ma.dm.id(args.deck)
    ma.model_name = 'Subtitles ({})'.format(args.deck)
    if args.language_name:
        ma.language_name = args.language_name
    if args.native_language_name:
        ma.native_language_name = args.native_language_name
    ma.subtitle_files = args.subtitles




if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Turn videos and subtitles into Anki2 decks..')
    parser.add_argument('-i', '--video', type=str, default='video.avi',
                        help='Video file input')
    parser.add_argument('-d', '--deck', type=str, default='Video deck',
                        help='Name of the deck inside the outputfile')
    parser.add_argument('-o', '--output', type=str, default='video_deck.apkg',
                        help='Name of the output file')
    parser.add_argument('-s', '--subtitles', type=str, nargs="+",
                        help='Subtitle files to use.')
    parser.add_argument('-c', '--language-codes', type=str, nargs="+",
                        help='''Codes for the languages. When using more than \
 one, keep these in line with the subtitle definitions.''')
    parser.add_argument('-l', '--language-names', type=str, nargs="+",
                        help='''Names of the languages.  When using more than \
 one, keep these in line with the subtitle definitions.''')
    parser.add_argument('-j', '--Japanese', action='store_true',
                        help='''Special treatment for Japanese.''')
    parser.add_argument('-z', '--Chinese', action='store_true',
                        help='''Special treatment for Chinese.''')
    args = parser.parse_args()
    ma = JimakuAnki()
    setup_from_args(ma, args)
    ma.add_dynamic_model()
    ma.process()
    ma.export()
    ma.cleanup()
