#!/usr/bin/env python3
# -*- mode: python ; coding: utf-8 -*-
#
# Copyright © 2012 Roland Sieker <ospalh@gmail.com>
#
# License: GNU AGPL, version 3 or later;
# http://www.gnu.org/copyleft/agpl.html

"""
Turn a video and sets of subtitles into an Anki2 deck.
"""

from subtitledecker import SubtitleDecker
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Turn videos and subtitles intto Anki2 decks..')
    parser.add_argument('-i', '--video', type=str, default='video.avi',
                        help='Video file input')
    parser.add_argument('-d', '--deck', type=str, default='Video deck',
                        help='Name of the deck inside the outputfile')
    parser.add_argument('-o', '--output', type=str, default='video_deck.apkg',
                        help='Name of the output file')
    parser.add_argument('-s', '--subtitle', type=str, nargs="+",
                        help='Subtitle files to use.')
    parser.add_argument('-l', '--language', type=str,
                        help='Code for the language you want to learn.')
    parser.add_argument('--language-name', type=str,
                        help='name of the language you want to learn.')
    parser.add_argument('-r', '--reading-field', action='store_true',
                        help='''Add a reading field. (Use this for Japanese \
and Chinese).''')
    parser.add_argument('-n', '--native-language', type=str,
                        help='Code for your native language')
    parser.add_argument('--native-language-name', type=str,
                        help='Name of your native language.')
    args = parser.parse_args()
    sd = SubtitleDecker(args)
    sd.process()
    sd.export()
    sd.rm_temp_collection()
